import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import chalk from "chalk";
import ora from "ora";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const templatesDir = path.resolve(__dirname, "../../templates");

export async function init(options = {}) {
  const targetDir = path.resolve(options.dir || ".");
  const force = options.force || false;

  const spinner = ora();
  const createdFiles = [];

  try {
    // 1. Create context directory with subdirectories
    const contextDir = path.join(targetDir, "context");

    if (fs.existsSync(contextDir) && !force) {
      spinner.warn(
        chalk.yellow(
          `Context directory already exists at ${contextDir}. Use --force to overwrite.`
        )
      );
      return;
    }

    const subdirs = [
      "architecture",
      "domains",
      "patterns",
      "workflows",
      "changelog",
      "templates",
    ];

    spinner.start("Creating context directory structure...");

    if (!fs.existsSync(contextDir)) {
      fs.mkdirSync(contextDir, { recursive: true });
    }

    for (const subdir of subdirs) {
      const subdirPath = path.join(contextDir, subdir);
      if (!fs.existsSync(subdirPath)) {
        fs.mkdirSync(subdirPath, { recursive: true });
      }
    }

    spinner.succeed(chalk.green("Context directory structure created"));
    createdFiles.push("context/");

    // 2. Copy template files from package templates to context/templates/
    spinner.start("Copying template files...");

    if (fs.existsSync(templatesDir)) {
      const templateFiles = fs.readdirSync(templatesDir);
      for (const file of templateFiles) {
        const src = path.join(templatesDir, file);
        const dest = path.join(contextDir, "templates", file);

        if (fs.statSync(src).isFile()) {
          const content = fs.readFileSync(src, "utf-8");
          fs.writeFileSync(dest, content);
          createdFiles.push(`context/templates/${file}`);
        }
      }
    }

    spinner.succeed(chalk.green("Template files copied"));

    // 3. Create AGENTS.md in project root (from template)
    spinner.start("Creating AGENTS.md...");

    const agentsMdPath = path.join(targetDir, "AGENTS.md");
    const agentsTemplatePath = path.join(templatesDir, "AGENTS.md");

    if (fs.existsSync(agentsTemplatePath)) {
      const template = fs.readFileSync(agentsTemplatePath, "utf-8");
      fs.writeFileSync(agentsMdPath, template);
    } else {
      // Fallback: generate a minimal AGENTS.md
      const today = new Date().toISOString().split("T")[0];
      fs.writeFileSync(
        agentsMdPath,
        `# Agent Instructions

> Root context file for AI agents working on this codebase.

## Overview

This is the root context file for AI agents. It provides orientation and links to detailed context files for each domain.

## Project Summary

<!-- TODO: Replace with your project description -->
[Your project] is a [type of application] that [core purpose].

## Tech Stack

| Layer | Technology |
|-------|------------|
| Frontend | <!-- TODO --> |
| Styling | <!-- TODO --> |
| State | <!-- TODO --> |
| Backend | <!-- TODO --> |
| API | <!-- TODO --> |

## Core Domains

<!-- TODO: List your business domains -->
- **[Domain 1]** - Description
- **[Domain 2]** - Description

## File Locations

\`\`\`
/
├── src/                    # Frontend code
├── context/                # AI context files
│   ├── architecture/       # System design docs
│   ├── domains/            # Domain context files
│   ├── patterns/           # Code patterns
│   ├── workflows/          # Dev process docs
│   ├── changelog/          # Change history
│   └── templates/          # Context file templates
└── package.json
\`\`\`

## Context Navigation

| Task Type | Primary Context |
|-----------|-----------------|
| New feature | \`context/workflows/FEATURE_DEVELOPMENT.md\` |
| Bug fix | \`context/workflows/BUG_FIXING.md\` |
| DB changes | \`context/workflows/DATABASE_MIGRATION.md\` |
| Testing | \`context/workflows/TESTING.md\` |

## Next Steps

Run \`npx context-graph-generator scan\` to auto-detect your tech stack and generate skeleton context files, then use the prompts in \`prompts/\` to deeply populate them with an AI agent.

---

*Generated by context-graph-generator on ${today}*
`
      );
    }

    createdFiles.push("AGENTS.md");
    spinner.succeed(chalk.green("AGENTS.md created"));

    // 4. Create CLAUDE.md that references AGENTS.md
    spinner.start("Creating CLAUDE.md...");

    const claudeMdPath = path.join(targetDir, "CLAUDE.md");
    fs.writeFileSync(claudeMdPath, "@AGENTS.md\n");
    createdFiles.push("CLAUDE.md");

    spinner.succeed(chalk.green("CLAUDE.md created (references @AGENTS.md)"));

    // 5. Create .cursorrules that references AGENTS.md
    spinner.start("Creating .cursorrules...");

    const cursorrulesPath = path.join(targetDir, ".cursorrules");
    fs.writeFileSync(cursorrulesPath, "@AGENTS.md\n");
    createdFiles.push(".cursorrules");

    spinner.succeed(
      chalk.green(".cursorrules created (references @AGENTS.md)")
    );

    // 6. Create context/WEEKLY_REVIEW.md with maintenance checklist
    spinner.start("Creating weekly review checklist...");

    const weeklyReviewPath = path.join(contextDir, "WEEKLY_REVIEW.md");
    const weeklyReviewTemplatePath = path.join(
      templatesDir,
      "WEEKLY_REVIEW.md"
    );

    if (fs.existsSync(weeklyReviewTemplatePath)) {
      const template = fs.readFileSync(weeklyReviewTemplatePath, "utf-8");
      fs.writeFileSync(weeklyReviewPath, template);
    } else {
      const today = new Date().toISOString().split("T")[0];
      fs.writeFileSync(
        weeklyReviewPath,
        `# Weekly Context Review Checklist

Use this checklist for weekly maintenance of the context graph.

## When to Review

- End of each week
- After major feature releases
- After significant refactoring

---

## Accuracy Check

### Code Locations
- [ ] Spot check 5 file paths per domain - do they still exist?
- [ ] Verify function names in docs match implementation
- [ ] Check component locations are accurate

### Business Rules
- [ ] Status transition rules match code
- [ ] Access control rules documented correctly
- [ ] Integration flows match implementation

---

## Completeness Check

### New Features
- [ ] All features merged this week have context updates
- [ ] New components have pattern documentation
- [ ] New hooks are documented

### Gotchas
- [ ] Bugs fixed this week added as gotchas?
- [ ] Edge cases documented?

---

## Quick Verification

\`\`\`bash
npx context-graph-generator verify
git log --oneline -10 -- context/
\`\`\`

---

*Generated by context-graph-generator on ${today}*
`
      );
    }

    createdFiles.push("context/WEEKLY_REVIEW.md");
    spinner.succeed(chalk.green("Weekly review checklist created"));

    // 7. Create starter changelog entry
    spinner.start("Creating changelog entry...");

    const now = new Date();
    const yearMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
    const today = now.toISOString().split("T")[0];
    const changelogPath = path.join(
      contextDir,
      "changelog",
      `${yearMonth}.md`
    );

    fs.writeFileSync(
      changelogPath,
      `# Context Changelog: ${yearMonth}

> **Type:** changelog
> **Owner:** shared
> **Status:** active

## Week of ${today}

### Summary

Context graph initialized for this project.

### Files Changed

| File | Reason |
|------|--------|
| \`AGENTS.md\` | Initial creation |
| \`CLAUDE.md\` | Initial creation |
| \`.cursorrules\` | Initial creation |
| \`context/\` | Directory structure created |

---

*Created: ${today}*
*Last Updated: ${today}*
`
    );

    createdFiles.push(`context/changelog/${yearMonth}.md`);
    spinner.succeed(chalk.green("Changelog entry created"));

    // Print summary
    console.log("\n");
    console.log(chalk.bold.green("Context graph initialized successfully!\n"));
    console.log(chalk.bold("Created files:"));
    console.log("");

    for (const file of createdFiles) {
      console.log(chalk.cyan(`  + ${file}`));
    }

    console.log("");
    console.log(chalk.bold("Next steps:"));
    console.log(
      chalk.gray("  1. Run ") +
        chalk.white("npx context-graph-generator scan") +
        chalk.gray(" to detect your stack and generate skeleton context files")
    );
    console.log(
      chalk.gray(
        "  2. Use the prompts in prompts/ to populate context files with an AI agent"
      )
    );
    console.log(
      chalk.gray("  3. Run ") +
        chalk.white("npx context-graph-generator verify") +
        chalk.gray(" to check completeness")
    );
    console.log("");
  } catch (error) {
    spinner.fail(
      chalk.red(`Error initializing context graph: ${error.message}`)
    );
    console.error(error);
    process.exit(1);
  }
}
